NrModeSwitcher: Implement debug flags instead of from framework
* Debug flags defined in https://github.com/SunOS-Project/android_sun-sdk/blob/varuna/frameworks/src/org/sun/os/DebugConstants.java#L108

* For fix:
packages/apps/NrModeSwitcher/src/org/sun/nrmode/util/Constants.kt:11:16: error: unresolved reference: os
import org.sun.os.DebugConstants.DEBUG_NR_MODE
               ^
packages/apps/NrModeSwitcher/src/org/sun/nrmode/util/Constants.kt:33:9: error: unresolved reference: DEBUG_NR_MODE
    if (DEBUG_NR_MODE) {